### ISSUE TITLE
why do you use GCP Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [aina-saa/json2pubsub#25]
Hi, I am reading your project and I love this project
I have a question, why do you choose GCP Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose GCP Pubsub instead of others like RabbitMQ or Kafka

**Comment by braincow** [comment]
Hi, the project that uses this tool as a part of its data ingestion pipeline runs in GCP and thus using PubSub was the most obvious choice there. Similar tool as this could be written for other message-brokers too, but this tool is meant to be used with GCP PubSub only.
